CREATE TABLE devices (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         created_at TIMESTAMP(6),
                         device_name VARCHAR(255),
                         device_token VARCHAR(255) NOT NULL,
                         last_seen_at TIMESTAMP(6),
                         operating_system VARCHAR(255),
                         CONSTRAINT uk_devices_device_token UNIQUE (device_token)
);

CREATE TABLE system_stats_entity (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     cpu_usage DOUBLE PRECISION NOT NULL,
                                     created_at TIMESTAMP(6),
                                     total_memory_mb DOUBLE PRECISION NOT NULL,
                                     used_memory_mb DOUBLE PRECISION NOT NULL,
                                     device_id BIGINT,
                                     CONSTRAINT fk_system_stats_device
                                         FOREIGN KEY (device_id)
                                             REFERENCES devices (id)
);

CREATE INDEX idx_system_stats_device_id
    ON system_stats_entity (device_id);