CREATE TABLE process_stats_entity (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      memory_usage_mb DOUBLE PRECISION NOT NULL,
                                      process_id INTEGER NOT NULL,
                                      process_name VARCHAR(255),
                                      system_stats_id BIGINT,
                                      CONSTRAINT fk_process_stats_system_stats
                                          FOREIGN KEY (system_stats_id)
                                              REFERENCES system_stats_entity (id)
);

CREATE INDEX idx_process_stats_system_stats_id
    ON process_stats_entity (system_stats_id);