CREATE TABLE diagnostic_report_entity (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          health_score INTEGER NOT NULL,
                                          status VARCHAR(255),
                                          summary TEXT,
                                          detected_issues TEXT,
                                          recommendations TEXT,
                                          created_at TIMESTAMP(6),
                                          device_id BIGINT,
                                          system_stats_id BIGINT,
                                          CONSTRAINT fk_diagnostic_report_device
                                              FOREIGN KEY (device_id)
                                                  REFERENCES devices (id),
                                          CONSTRAINT fk_diagnostic_report_system_stats
                                              FOREIGN KEY (system_stats_id)
                                                  REFERENCES system_stats_entity (id)
);

CREATE INDEX idx_diagnostic_report_device_id
    ON diagnostic_report_entity (device_id);

CREATE INDEX idx_diagnostic_report_system_stats_id
    ON diagnostic_report_entity (system_stats_id);

CREATE INDEX idx_diagnostic_report_created_at
    ON diagnostic_report_entity (created_at);